In [1]:
%matplotlib inline

import numpy as np 
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
from torch.utils.data import DataLoader

import torchvision
import torchvision.transforms as transforms

In [2]:
# Definir a arquitetura MLP

class MLP(nn.Module):

    def __init__(self, layers):
        super(MLP, self).__init__()
        self.layers = layers
        self.fc1 = nn.Linear(2, 10)
        self.fc2 = nn.Linear(10, 4)
        self.activation_function = torch.nn.LeakyReLU()
        
    def forward(self, x):
        x = x.view(-1, 2)
        x = self.activation_function(self.fc1(x))
        x = self.activation_function(self.fc2(x))
        return x

In [3]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model = MLP([]).to(device)
print(device)
print(model)

# Definir otimizador e loss
# Nota: testar outros otimizadores e funções de loss (em particular cross entropy)
optimizer = torch.optim.SGD(model.parameters(), lr = 0.1)
loss_fn = torch.nn.CrossEntropyLoss().cuda()

cuda:0
MLP(
  (fc1): Linear(in_features=2, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=4, bias=True)
  (activation_function): LeakyReLU(negative_slope=0.01)
)


In [4]:

labels = [[0], [1], [2], [3]]
inputs = [[1,1], [1,0], [0,1], [0,0]]
train = []
for i in range(4):
    train.append((inputs[i],labels[i]))

In [5]:
import random

for epoch in range(1000):
    error = 0
#     random.shuffle(train)
    for i, (inputs, labels) in enumerate(train):
        inputs = torch.Tensor(np.array(inputs)).to(device)
        labels = torch.LongTensor(np.array(labels)).to(device)
        optimizer.zero_grad()
        y_pred = model(inputs)
        loss = loss_fn(y_pred, labels)
        loss.backward()
        optimizer.step()
        error+=loss

    print(epoch, error/4)

0 tensor(1.3948, device='cuda:0', grad_fn=<DivBackward0>)
1 tensor(1.3861, device='cuda:0', grad_fn=<DivBackward0>)
2 tensor(1.3861, device='cuda:0', grad_fn=<DivBackward0>)
3 tensor(1.3861, device='cuda:0', grad_fn=<DivBackward0>)
4 tensor(1.3861, device='cuda:0', grad_fn=<DivBackward0>)
5 tensor(1.3861, device='cuda:0', grad_fn=<DivBackward0>)
6 tensor(1.3861, device='cuda:0', grad_fn=<DivBackward0>)
7 tensor(1.3861, device='cuda:0', grad_fn=<DivBackward0>)
8 tensor(1.3861, device='cuda:0', grad_fn=<DivBackward0>)
9 tensor(1.3861, device='cuda:0', grad_fn=<DivBackward0>)
10 tensor(1.3861, device='cuda:0', grad_fn=<DivBackward0>)
11 tensor(1.3861, device='cuda:0', grad_fn=<DivBackward0>)
12 tensor(1.3861, device='cuda:0', grad_fn=<DivBackward0>)
13 tensor(1.3861, device='cuda:0', grad_fn=<DivBackward0>)
14 tensor(1.3861, device='cuda:0', grad_fn=<DivBackward0>)
15 tensor(1.3860, device='cuda:0', grad_fn=<DivBackward0>)
16 tensor(1.3860, device='cuda:0', grad_fn=<DivBackward0>)
17 tens

144 tensor(0.7581, device='cuda:0', grad_fn=<DivBackward0>)
145 tensor(0.7552, device='cuda:0', grad_fn=<DivBackward0>)
146 tensor(0.7385, device='cuda:0', grad_fn=<DivBackward0>)
147 tensor(0.7340, device='cuda:0', grad_fn=<DivBackward0>)
148 tensor(0.7376, device='cuda:0', grad_fn=<DivBackward0>)
149 tensor(0.7324, device='cuda:0', grad_fn=<DivBackward0>)
150 tensor(0.7335, device='cuda:0', grad_fn=<DivBackward0>)
151 tensor(0.7365, device='cuda:0', grad_fn=<DivBackward0>)
152 tensor(0.7332, device='cuda:0', grad_fn=<DivBackward0>)
153 tensor(0.7273, device='cuda:0', grad_fn=<DivBackward0>)
154 tensor(0.7245, device='cuda:0', grad_fn=<DivBackward0>)
155 tensor(0.7223, device='cuda:0', grad_fn=<DivBackward0>)
156 tensor(0.7203, device='cuda:0', grad_fn=<DivBackward0>)
157 tensor(0.7187, device='cuda:0', grad_fn=<DivBackward0>)
158 tensor(0.7172, device='cuda:0', grad_fn=<DivBackward0>)
159 tensor(0.7203, device='cuda:0', grad_fn=<DivBackward0>)
160 tensor(0.7377, device='cuda:0', grad

297 tensor(0.1456, device='cuda:0', grad_fn=<DivBackward0>)
298 tensor(0.1381, device='cuda:0', grad_fn=<DivBackward0>)
299 tensor(0.1294, device='cuda:0', grad_fn=<DivBackward0>)
300 tensor(0.1236, device='cuda:0', grad_fn=<DivBackward0>)
301 tensor(0.1162, device='cuda:0', grad_fn=<DivBackward0>)
302 tensor(0.1101, device='cuda:0', grad_fn=<DivBackward0>)
303 tensor(0.1043, device='cuda:0', grad_fn=<DivBackward0>)
304 tensor(0.1002, device='cuda:0', grad_fn=<DivBackward0>)
305 tensor(0.0948, device='cuda:0', grad_fn=<DivBackward0>)
306 tensor(0.0899, device='cuda:0', grad_fn=<DivBackward0>)
307 tensor(0.0861, device='cuda:0', grad_fn=<DivBackward0>)
308 tensor(0.0821, device='cuda:0', grad_fn=<DivBackward0>)
309 tensor(0.0781, device='cuda:0', grad_fn=<DivBackward0>)
310 tensor(0.0750, device='cuda:0', grad_fn=<DivBackward0>)
311 tensor(0.0718, device='cuda:0', grad_fn=<DivBackward0>)
312 tensor(0.0689, device='cuda:0', grad_fn=<DivBackward0>)
313 tensor(0.0659, device='cuda:0', grad

462 tensor(0.0067, device='cuda:0', grad_fn=<DivBackward0>)
463 tensor(0.0067, device='cuda:0', grad_fn=<DivBackward0>)
464 tensor(0.0066, device='cuda:0', grad_fn=<DivBackward0>)
465 tensor(0.0066, device='cuda:0', grad_fn=<DivBackward0>)
466 tensor(0.0066, device='cuda:0', grad_fn=<DivBackward0>)
467 tensor(0.0065, device='cuda:0', grad_fn=<DivBackward0>)
468 tensor(0.0065, device='cuda:0', grad_fn=<DivBackward0>)
469 tensor(0.0064, device='cuda:0', grad_fn=<DivBackward0>)
470 tensor(0.0064, device='cuda:0', grad_fn=<DivBackward0>)
471 tensor(0.0063, device='cuda:0', grad_fn=<DivBackward0>)
472 tensor(0.0063, device='cuda:0', grad_fn=<DivBackward0>)
473 tensor(0.0063, device='cuda:0', grad_fn=<DivBackward0>)
474 tensor(0.0062, device='cuda:0', grad_fn=<DivBackward0>)
475 tensor(0.0062, device='cuda:0', grad_fn=<DivBackward0>)
476 tensor(0.0061, device='cuda:0', grad_fn=<DivBackward0>)
477 tensor(0.0061, device='cuda:0', grad_fn=<DivBackward0>)
478 tensor(0.0061, device='cuda:0', grad

610 tensor(0.0033, device='cuda:0', grad_fn=<DivBackward0>)
611 tensor(0.0032, device='cuda:0', grad_fn=<DivBackward0>)
612 tensor(0.0032, device='cuda:0', grad_fn=<DivBackward0>)
613 tensor(0.0032, device='cuda:0', grad_fn=<DivBackward0>)
614 tensor(0.0032, device='cuda:0', grad_fn=<DivBackward0>)
615 tensor(0.0032, device='cuda:0', grad_fn=<DivBackward0>)
616 tensor(0.0032, device='cuda:0', grad_fn=<DivBackward0>)
617 tensor(0.0032, device='cuda:0', grad_fn=<DivBackward0>)
618 tensor(0.0032, device='cuda:0', grad_fn=<DivBackward0>)
619 tensor(0.0032, device='cuda:0', grad_fn=<DivBackward0>)
620 tensor(0.0031, device='cuda:0', grad_fn=<DivBackward0>)
621 tensor(0.0031, device='cuda:0', grad_fn=<DivBackward0>)
622 tensor(0.0031, device='cuda:0', grad_fn=<DivBackward0>)
623 tensor(0.0031, device='cuda:0', grad_fn=<DivBackward0>)
624 tensor(0.0031, device='cuda:0', grad_fn=<DivBackward0>)
625 tensor(0.0031, device='cuda:0', grad_fn=<DivBackward0>)
626 tensor(0.0031, device='cuda:0', grad

761 tensor(0.0021, device='cuda:0', grad_fn=<DivBackward0>)
762 tensor(0.0021, device='cuda:0', grad_fn=<DivBackward0>)
763 tensor(0.0021, device='cuda:0', grad_fn=<DivBackward0>)
764 tensor(0.0021, device='cuda:0', grad_fn=<DivBackward0>)
765 tensor(0.0021, device='cuda:0', grad_fn=<DivBackward0>)
766 tensor(0.0021, device='cuda:0', grad_fn=<DivBackward0>)
767 tensor(0.0021, device='cuda:0', grad_fn=<DivBackward0>)
768 tensor(0.0020, device='cuda:0', grad_fn=<DivBackward0>)
769 tensor(0.0020, device='cuda:0', grad_fn=<DivBackward0>)
770 tensor(0.0020, device='cuda:0', grad_fn=<DivBackward0>)
771 tensor(0.0020, device='cuda:0', grad_fn=<DivBackward0>)
772 tensor(0.0020, device='cuda:0', grad_fn=<DivBackward0>)
773 tensor(0.0020, device='cuda:0', grad_fn=<DivBackward0>)
774 tensor(0.0020, device='cuda:0', grad_fn=<DivBackward0>)
775 tensor(0.0020, device='cuda:0', grad_fn=<DivBackward0>)
776 tensor(0.0020, device='cuda:0', grad_fn=<DivBackward0>)
777 tensor(0.0020, device='cuda:0', grad

898 tensor(0.0016, device='cuda:0', grad_fn=<DivBackward0>)
899 tensor(0.0015, device='cuda:0', grad_fn=<DivBackward0>)
900 tensor(0.0015, device='cuda:0', grad_fn=<DivBackward0>)
901 tensor(0.0015, device='cuda:0', grad_fn=<DivBackward0>)
902 tensor(0.0015, device='cuda:0', grad_fn=<DivBackward0>)
903 tensor(0.0015, device='cuda:0', grad_fn=<DivBackward0>)
904 tensor(0.0015, device='cuda:0', grad_fn=<DivBackward0>)
905 tensor(0.0015, device='cuda:0', grad_fn=<DivBackward0>)
906 tensor(0.0015, device='cuda:0', grad_fn=<DivBackward0>)
907 tensor(0.0015, device='cuda:0', grad_fn=<DivBackward0>)
908 tensor(0.0015, device='cuda:0', grad_fn=<DivBackward0>)
909 tensor(0.0015, device='cuda:0', grad_fn=<DivBackward0>)
910 tensor(0.0015, device='cuda:0', grad_fn=<DivBackward0>)
911 tensor(0.0015, device='cuda:0', grad_fn=<DivBackward0>)
912 tensor(0.0015, device='cuda:0', grad_fn=<DivBackward0>)
913 tensor(0.0015, device='cuda:0', grad_fn=<DivBackward0>)
914 tensor(0.0015, device='cuda:0', grad

In [6]:
for i, (inputs, labels) in enumerate(train):
    inputs = torch.Tensor(np.array(inputs)).to(device)
    labels = torch.Tensor(np.array(labels)).to(device)
    print(model(inputs))
    print(labels)
    print()

tensor([[8.9820, 0.7424, 0.9731, 0.8013]], device='cuda:0',
       grad_fn=<LeakyReluBackward0>)
tensor([0.], device='cuda:0')

tensor([[ 4.3841, 12.0332, -0.1060,  4.2348]], device='cuda:0',
       grad_fn=<LeakyReluBackward0>)
tensor([1.], device='cuda:0')

tensor([[ 4.0785, -0.0949, 11.7116,  4.1113]], device='cuda:0',
       grad_fn=<LeakyReluBackward0>)
tensor([2.], device='cuda:0')

tensor([[-1.0818e-04,  4.8235e-05, -7.7803e-06,  7.1181e+00]], device='cuda:0',
       grad_fn=<LeakyReluBackward0>)
tensor([3.], device='cuda:0')

